export const keywords = {
  app: '@app-a',
  controller: 'Controller',
  controllerLcase: 'controller',
  create: 'Create',
  footer: 'Footer',
  header: 'Header',
  id: 'Id',
  imports: 'Imports',
  index: 'index',
  input: 'Input',
  interfaceUcFirst: 'Interface',
  interfacePrefix: 'I',
  jsDoc: 'JsDoc',
  model: 'Model',
  output: 'Output',
  read: 'Read',
  template: 'Template',
  tryCatch: 'TryCatch',
  typesObjectId: 'Types.ObjectId',
  update: 'Update',
  validationSchema: 'ValidationSchema',
};
